version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd app
      - npm install
  build:
    commands:
      - echo Building app...
      - npm run build
  post_build:
    commands:
      - echo Build completed!
artifacts:
  files:
    - app/**/*
